### ISSUE TITLE
A lot of flickering on old hardware

### ISSUE THREAD

**Issue by txgk** [n-ivkovic/treedude#3]
I have Intel Celeron N3350 and treedude flickers a lot in some moments of the game. It is probably not a bug, but maybe there is a way to redraw screen more efficiently and less frequent? I don't ask to slow down gameplay and popup titles (I like the pace at which everything is drawn), maybe it just can be made less processor intensive.

I attached sample of gameplay with a lot of flickering

https://user-images.githubusercontent.com/96500731/174428489-5d9faf30-9c63-4cd6-b3cb-6a99792ea3c2.mp4

**Comment by n-ivkovic** [comment]
I've made a commit to develop (4df53ed6aba0378fc01f4dea28900ef15c8717db) that should further improve drawing performance. Let me know if the fix has sufficiently decreased the flickering or if you believe more can be done.

**Comment by txgk** [comment]
To be honest I didn't notice any change after [4df53ed](https://github.com/n-ivkovic/treedude/commit/4df53ed6aba0378fc01f4dea28900ef15c8717db). Most likely this is an optimization, but my eyes failed to notice it. Flickering while chopping a tree is tolerable enough, but when title is displayed after death, I begin to praise the Lord that I am not an epileptic :D

I'm sure it is possible to draw more efficiently specifically after death, because the only areas that update during this period are TREE DUDE title and [PRESS ENTER TO RESTART] text, and as far as I can see, they are not updated every couple of milliseconds, but only every few hundred milliseconds. Maybe it is possible to somehow redraw screen on demand (when these two areas do update) rather than redraw it iteratively every few milliseconds?

**Comment by txgk** [comment]
Apparently this change requires a significant refactoring of the entire codebase because all drawing functions depend on the main time counter, so I don’t even know if the functionality will suffer due to such "optimization". You can close this issue because I have no right to ask to rewrite the entire project)

**Comment by n-ivkovic** [comment]
I've made another commit to develop (9189fae9587101c99038707ce3f43de78138e3d8) that ensures the screen is redrawn only when the stage update functions indicates it is required.

I've implemented this optimisation mainly in the intro and game over stages so you should see the largest amount of improvement there. For example the game over stage, when not fading in/out, will now be redrawn 4 times per second (now 2-3 times with 839f3bb20ba6fb3dc7129180bf011faa12cf5c67) as opposed to 20 times. I haven't implemented much of this screen drawing optimisation in main game stage since there's a lot of changes going on each frame to keep track of. Plus at the pace the game is played at there's hardly any frames where a screen redraw isn't required, so any optimisation I include won't benefit the overall performance too much. Maybe something to look into another day.

Here's a recording of a build which visually shows the optimisation. Whenever the text colours are reversed it means that the screen redraw for that frame wasn't necessary, and with this new optmisation will no longer be drawn.

https://user-images.githubusercontent.com/39162564/174514066-6b811d62-890c-4383-b9a6-b0b34a3ca87f.mp4

**Comment by txgk** [comment]
This is a great optimization, nice! Now screen on the after-death stage almost does not flicker. I agree that it is better to avoid these drawing optimizations in main game stage because it can ruin "sense of speed". Cheers :)

By the way here is the gameplay after https://github.com/n-ivkovic/treedude/commit/839f3bb20ba6fb3dc7129180bf011faa12cf5c67 Just compare it to what it was. Awesome)

https://user-images.githubusercontent.com/96500731/174521987-f0db7d01-ae42-4a27-944c-86d2a5573523.mp4
